<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerScwnxuz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerScwnxuz/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerScwnxuz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerScwnxuz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerScwnxuz\appProdProjectContainer([
    'container.build_hash' => 'Scwnxuz',
    'container.build_id' => 'e516da98',
    'container.build_time' => 1602774508,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerScwnxuz');
