<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHwn23em\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHwn23em/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHwn23em.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHwn23em\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHwn23em\appDevDebugProjectContainer([
    'container.build_hash' => 'Hwn23em',
    'container.build_id' => '543a7add',
    'container.build_time' => 1602805612,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHwn23em');
